/* eslint-disable no-restricted-globals */
/* global self */

import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NavigationRoute } from 'workbox-routing';

clientsClaim();

// Precache all of the assets generated by the build process.
precacheAndRoute(self.__WB_MANIFEST || []);

// App-shell style routing for navigation requests.
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');

registerRoute(
  new NavigationRoute(createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html'), {
    denylist: [],
  })
);

// Skip waiting so new versions activate faster after all tabs close.
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
